# Q11: IT Infrastructure Impact
PREFIX btb: <http://basetype.benchmark/ontology#>

SELECT ?equipment_id ?equipment_name ?equipment_type
WHERE {
    ?ups btb:id ?upsId .
    ?ups btb:feeds+ ?target .

    ?target btb:id ?equipment_id ;
            btb:name ?equipment_name ;
            btb:equipmentType ?equipment_type .

    FILTER(?equipment_type IN ("RackServer", "NetworkSwitch", "StorageArray"))
}
ORDER BY ?equipment_type ?equipment_id
