PREFIX ex: <http://example.org/>
PREFIX ext: <http://example.org/type/>

# Détection des points et équipements orphelins
SELECT ?entity_type ?id ?name
WHERE {
  {
    SELECT "Point" AS ?entity_type ?p AS ?id ?label AS ?name
    WHERE {
      ?p a ext:Point .
      OPTIONAL { ?p ex:name ?label }
      FILTER NOT EXISTS { ?parent ex:HAS_POINT ?p }
    }
  }
  UNION
  {
    SELECT "Equipment" AS ?entity_type ?e AS ?id ?label AS ?name
    WHERE {
      ?e a ext:Equipment .
      OPTIONAL { ?e ex:name ?label }
      FILTER NOT EXISTS { ?e ex:LOCATED_IN ?space }
    }
  }
}
ORDER BY ?entity_type ?id
